services:
  caddy:
    image: openmodelica/openmodelica:v1.22.4-minimal
    restart: always
    ports:
      - "8913:8913"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      #      - ./site:/srv
      #      - caddy_data:/data
      - ./html:/var/www/html
#      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: