// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.28.2
// source: compiler.proto

package smc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetErrorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetErrorsRequest) Reset() {
	*x = GetErrorsRequest{}
	mi := &file_compiler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErrorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErrorsRequest) ProtoMessage() {}

func (x *GetErrorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErrorsRequest.ProtoReflect.Descriptor instead.
func (*GetErrorsRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{0}
}

type GetErrorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageList   []*ErrorMessage        `protobuf:"bytes,1,rep,name=messageList,proto3" json:"messageList,omitempty"` // 错误信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetErrorsResponse) Reset() {
	*x = GetErrorsResponse{}
	mi := &file_compiler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErrorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErrorsResponse) ProtoMessage() {}

func (x *GetErrorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErrorsResponse.ProtoReflect.Descriptor instead.
func (*GetErrorsResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{1}
}

func (x *GetErrorsResponse) GetMessageList() []*ErrorMessage {
	if x != nil {
		return x.MessageList
	}
	return nil
}

type SetClassAnnotationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClassName          string                 `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"`                    // 模型名称
	SetClassAnnotation *Argument              `protobuf:"bytes,11,opt,name=SetClassAnnotation,proto3" json:"SetClassAnnotation,omitempty"` // 更新元素对象
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetClassAnnotationRequest) Reset() {
	*x = SetClassAnnotationRequest{}
	mi := &file_compiler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClassAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClassAnnotationRequest) ProtoMessage() {}

func (x *SetClassAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClassAnnotationRequest.ProtoReflect.Descriptor instead.
func (*SetClassAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{2}
}

func (x *SetClassAnnotationRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *SetClassAnnotationRequest) GetSetClassAnnotation() *Argument {
	if x != nil {
		return x.SetClassAnnotation
	}
	return nil
}

type SetClassAnnotationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClassAnnotationResponse) Reset() {
	*x = SetClassAnnotationResponse{}
	mi := &file_compiler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClassAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClassAnnotationResponse) ProtoMessage() {}

func (x *SetClassAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClassAnnotationResponse.ProtoReflect.Descriptor instead.
func (*SetClassAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{3}
}

func (x *SetClassAnnotationResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type DeleteConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"`
	Left          string                 `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right         string                 `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnectionRequest) Reset() {
	*x = DeleteConnectionRequest{}
	mi := &file_compiler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectionRequest) ProtoMessage() {}

func (x *DeleteConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteConnectionRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteConnectionRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *DeleteConnectionRequest) GetLeft() string {
	if x != nil {
		return x.Left
	}
	return ""
}

func (x *DeleteConnectionRequest) GetRight() string {
	if x != nil {
		return x.Right
	}
	return ""
}

type DeleteConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnectionResponse) Reset() {
	*x = DeleteConnectionResponse{}
	mi := &file_compiler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectionResponse) ProtoMessage() {}

func (x *DeleteConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteConnectionResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteConnectionResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type SetConnectionAnnotationRequest struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	SetConnectionAnnotation *SetConnectionAnnotation `protobuf:"bytes,1,opt,name=SetConnectionAnnotation,proto3" json:"SetConnectionAnnotation,omitempty"` // 更新元素对象
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SetConnectionAnnotationRequest) Reset() {
	*x = SetConnectionAnnotationRequest{}
	mi := &file_compiler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConnectionAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectionAnnotationRequest) ProtoMessage() {}

func (x *SetConnectionAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectionAnnotationRequest.ProtoReflect.Descriptor instead.
func (*SetConnectionAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{6}
}

func (x *SetConnectionAnnotationRequest) GetSetConnectionAnnotation() *SetConnectionAnnotation {
	if x != nil {
		return x.SetConnectionAnnotation
	}
	return nil
}

type SetConnectionAnnotationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConnectionAnnotationResponse) Reset() {
	*x = SetConnectionAnnotationResponse{}
	mi := &file_compiler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConnectionAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectionAnnotationResponse) ProtoMessage() {}

func (x *SetConnectionAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectionAnnotationResponse.ProtoReflect.Descriptor instead.
func (*SetConnectionAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{7}
}

func (x *SetConnectionAnnotationResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type AddConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddConnection *AddConnection         `protobuf:"bytes,1,opt,name=addConnection,proto3" json:"addConnection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConnectionRequest) Reset() {
	*x = AddConnectionRequest{}
	mi := &file_compiler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConnectionRequest) ProtoMessage() {}

func (x *AddConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConnectionRequest.ProtoReflect.Descriptor instead.
func (*AddConnectionRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{8}
}

func (x *AddConnectionRequest) GetAddConnection() *AddConnection {
	if x != nil {
		return x.AddConnection
	}
	return nil
}

type AddConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConnectionResponse) Reset() {
	*x = AddConnectionResponse{}
	mi := &file_compiler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConnectionResponse) ProtoMessage() {}

func (x *AddConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConnectionResponse.ProtoReflect.Descriptor instead.
func (*AddConnectionResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{9}
}

func (x *AddConnectionResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type DeleteElementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"`     // 模型名称
	ElementName   string                 `protobuf:"bytes,2,opt,name=elementName,proto3" json:"elementName,omitempty"` // 模型组件名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteElementRequest) Reset() {
	*x = DeleteElementRequest{}
	mi := &file_compiler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteElementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteElementRequest) ProtoMessage() {}

func (x *DeleteElementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteElementRequest.ProtoReflect.Descriptor instead.
func (*DeleteElementRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteElementRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *DeleteElementRequest) GetElementName() string {
	if x != nil {
		return x.ElementName
	}
	return ""
}

type DeleteElementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteElementResponse) Reset() {
	*x = DeleteElementResponse{}
	mi := &file_compiler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteElementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteElementResponse) ProtoMessage() {}

func (x *DeleteElementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteElementResponse.ProtoReflect.Descriptor instead.
func (*DeleteElementResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteElementResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type SetElementAnnotationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SetElementAnnotation *SetElementAnnotation  `protobuf:"bytes,1,opt,name=setElementAnnotation,proto3" json:"setElementAnnotation,omitempty"` // 更新元素对象的注解信息
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SetElementAnnotationRequest) Reset() {
	*x = SetElementAnnotationRequest{}
	mi := &file_compiler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetElementAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetElementAnnotationRequest) ProtoMessage() {}

func (x *SetElementAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetElementAnnotationRequest.ProtoReflect.Descriptor instead.
func (*SetElementAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{12}
}

func (x *SetElementAnnotationRequest) GetSetElementAnnotation() *SetElementAnnotation {
	if x != nil {
		return x.SetElementAnnotation
	}
	return nil
}

type SetElementAnnotationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetElementAnnotationResponse) Reset() {
	*x = SetElementAnnotationResponse{}
	mi := &file_compiler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetElementAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetElementAnnotationResponse) ProtoMessage() {}

func (x *SetElementAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetElementAnnotationResponse.ProtoReflect.Descriptor instead.
func (*SetElementAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{13}
}

func (x *SetElementAnnotationResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type AddElementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddElement    *AddElement            `protobuf:"bytes,1,opt,name=addElement,proto3" json:"addElement,omitempty"` // 新增元素对象
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddElementRequest) Reset() {
	*x = AddElementRequest{}
	mi := &file_compiler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddElementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddElementRequest) ProtoMessage() {}

func (x *AddElementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddElementRequest.ProtoReflect.Descriptor instead.
func (*AddElementRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{14}
}

func (x *AddElementRequest) GetAddElement() *AddElement {
	if x != nil {
		return x.AddElement
	}
	return nil
}

type AddElementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddElementResponse) Reset() {
	*x = AddElementResponse{}
	mi := &file_compiler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddElementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddElementResponse) ProtoMessage() {}

func (x *AddElementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddElementResponse.ProtoReflect.Descriptor instead.
func (*AddElementResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{15}
}

func (x *AddElementResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetModelicaPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelicaPathRequest) Reset() {
	*x = GetModelicaPathRequest{}
	mi := &file_compiler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelicaPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelicaPathRequest) ProtoMessage() {}

func (x *GetModelicaPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelicaPathRequest.ProtoReflect.Descriptor instead.
func (*GetModelicaPathRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{16}
}

type GetModelicaPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathList      []string               `protobuf:"bytes,1,rep,name=pathList,proto3" json:"pathList,omitempty"` // 路径列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelicaPathResponse) Reset() {
	*x = GetModelicaPathResponse{}
	mi := &file_compiler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelicaPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelicaPathResponse) ProtoMessage() {}

func (x *GetModelicaPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelicaPathResponse.ProtoReflect.Descriptor instead.
func (*GetModelicaPathResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{17}
}

func (x *GetModelicaPathResponse) GetPathList() []string {
	if x != nil {
		return x.PathList
	}
	return nil
}

type SetModelicaPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // 路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelicaPathRequest) Reset() {
	*x = SetModelicaPathRequest{}
	mi := &file_compiler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelicaPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelicaPathRequest) ProtoMessage() {}

func (x *SetModelicaPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelicaPathRequest.ProtoReflect.Descriptor instead.
func (*SetModelicaPathRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{18}
}

func (x *SetModelicaPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SetModelicaPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 设置结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelicaPathResponse) Reset() {
	*x = SetModelicaPathResponse{}
	mi := &file_compiler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelicaPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelicaPathResponse) ProtoMessage() {}

func (x *SetModelicaPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelicaPathResponse.ProtoReflect.Descriptor instead.
func (*SetModelicaPathResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{19}
}

func (x *SetModelicaPathResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type LoadLibraryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   string                 `protobuf:"bytes,1,opt,name=packageName,proto3" json:"packageName,omitempty"` // 模型路径
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`         // 模型版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadLibraryRequest) Reset() {
	*x = LoadLibraryRequest{}
	mi := &file_compiler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadLibraryRequest) ProtoMessage() {}

func (x *LoadLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadLibraryRequest.ProtoReflect.Descriptor instead.
func (*LoadLibraryRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{20}
}

func (x *LoadLibraryRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *LoadLibraryRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type LoadLibraryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`        // 返回的信息
	Result        bool                   `protobuf:"varint,5,opt,name=result,proto3" json:"result,omitempty"` // 加载结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadLibraryResponse) Reset() {
	*x = LoadLibraryResponse{}
	mi := &file_compiler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadLibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadLibraryResponse) ProtoMessage() {}

func (x *LoadLibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadLibraryResponse.ProtoReflect.Descriptor instead.
func (*LoadLibraryResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{21}
}

func (x *LoadLibraryResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoadLibraryResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetSubTypeOfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubTypeOfList []string               `protobuf:"bytes,1,rep,name=subTypeOfList,proto3" json:"subTypeOfList,omitempty"` // 子类型列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubTypeOfResponse) Reset() {
	*x = GetSubTypeOfResponse{}
	mi := &file_compiler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubTypeOfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubTypeOfResponse) ProtoMessage() {}

func (x *GetSubTypeOfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubTypeOfResponse.ProtoReflect.Descriptor instead.
func (*GetSubTypeOfResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{22}
}

func (x *GetSubTypeOfResponse) GetSubTypeOfList() []string {
	if x != nil {
		return x.SubTypeOfList
	}
	return nil
}

type GetSubTypeOfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"`   // 模型名称
	ParentName    string                 `protobuf:"bytes,2,opt,name=parentName,proto3" json:"parentName,omitempty"` // 约束限制，也是模型名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubTypeOfRequest) Reset() {
	*x = GetSubTypeOfRequest{}
	mi := &file_compiler_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubTypeOfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubTypeOfRequest) ProtoMessage() {}

func (x *GetSubTypeOfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubTypeOfRequest.ProtoReflect.Descriptor instead.
func (*GetSubTypeOfRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{23}
}

func (x *GetSubTypeOfRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *GetSubTypeOfRequest) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

type SaveModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 保存结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveModelResponse) Reset() {
	*x = SaveModelResponse{}
	mi := &file_compiler_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveModelResponse) ProtoMessage() {}

func (x *SaveModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveModelResponse.ProtoReflect.Descriptor instead.
func (*SaveModelResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{24}
}

func (x *SaveModelResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ParserModelCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"` // 模型名称
	ClassCode     string                 `protobuf:"bytes,2,opt,name=classCode,proto3" json:"classCode,omitempty"` // 模型代码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParserModelCodeRequest) Reset() {
	*x = ParserModelCodeRequest{}
	mi := &file_compiler_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserModelCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserModelCodeRequest) ProtoMessage() {}

func (x *ParserModelCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserModelCodeRequest.ProtoReflect.Descriptor instead.
func (*ParserModelCodeRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{25}
}

func (x *ParserModelCodeRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ParserModelCodeRequest) GetClassCode() string {
	if x != nil {
		return x.ClassCode
	}
	return ""
}

type ParserModelCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ClassDefinition       `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"` // 模型对象
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParserModelCodeResponse) Reset() {
	*x = ParserModelCodeResponse{}
	mi := &file_compiler_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserModelCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserModelCodeResponse) ProtoMessage() {}

func (x *ParserModelCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserModelCodeResponse.ProtoReflect.Descriptor instead.
func (*ParserModelCodeResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{26}
}

func (x *ParserModelCodeResponse) GetModel() *ClassDefinition {
	if x != nil {
		return x.Model
	}
	return nil
}

type ParserCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`             // 模型代码
	SourcePath    string                 `protobuf:"bytes,2,opt,name=sourcePath,proto3" json:"sourcePath,omitempty"` // 模型源码路径,实际是模型代码所在模型的名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParserCodeRequest) Reset() {
	*x = ParserCodeRequest{}
	mi := &file_compiler_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserCodeRequest) ProtoMessage() {}

func (x *ParserCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserCodeRequest.ProtoReflect.Descriptor instead.
func (*ParserCodeRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{27}
}

func (x *ParserCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ParserCodeRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

type ParserCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ClassDefinition       `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"` // 模型对象
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParserCodeResponse) Reset() {
	*x = ParserCodeResponse{}
	mi := &file_compiler_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserCodeResponse) ProtoMessage() {}

func (x *ParserCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserCodeResponse.ProtoReflect.Descriptor instead.
func (*ParserCodeResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{28}
}

func (x *ParserCodeResponse) GetModel() *ClassDefinition {
	if x != nil {
		return x.Model
	}
	return nil
}

type ClassNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"` // 模型名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassNameRequest) Reset() {
	*x = ClassNameRequest{}
	mi := &file_compiler_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassNameRequest) ProtoMessage() {}

func (x *ClassNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassNameRequest.ProtoReflect.Descriptor instead.
func (*ClassNameRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{29}
}

func (x *ClassNameRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type ModelASTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *ClassDefinition       `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"` // 模型名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelASTResponse) Reset() {
	*x = ModelASTResponse{}
	mi := &file_compiler_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelASTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelASTResponse) ProtoMessage() {}

func (x *ModelASTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelASTResponse.ProtoReflect.Descriptor instead.
func (*ModelASTResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{30}
}

func (x *ModelASTResponse) GetModel() *ClassDefinition {
	if x != nil {
		return x.Model
	}
	return nil
}

type ModelCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 模型源码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelCodeResponse) Reset() {
	*x = ModelCodeResponse{}
	mi := &file_compiler_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCodeResponse) ProtoMessage() {}

func (x *ModelCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCodeResponse.ProtoReflect.Descriptor instead.
func (*ModelCodeResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{31}
}

func (x *ModelCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ClassNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentName    string                 `protobuf:"bytes,1,opt,name=parentName,proto3" json:"parentName,omitempty"` // 模型名称列表
	IsAll         bool                   `protobuf:"varint,10,opt,name=isAll,proto3" json:"isAll,omitempty"`         // 加载结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassNamesRequest) Reset() {
	*x = ClassNamesRequest{}
	mi := &file_compiler_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassNamesRequest) ProtoMessage() {}

func (x *ClassNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassNamesRequest.ProtoReflect.Descriptor instead.
func (*ClassNamesRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{32}
}

func (x *ClassNamesRequest) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *ClassNamesRequest) GetIsAll() bool {
	if x != nil {
		return x.IsAll
	}
	return false
}

type ClassNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameList      []string               `protobuf:"bytes,1,rep,name=nameList,proto3" json:"nameList,omitempty"` // 模型名称列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassNamesResponse) Reset() {
	*x = ClassNamesResponse{}
	mi := &file_compiler_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassNamesResponse) ProtoMessage() {}

func (x *ClassNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassNamesResponse.ProtoReflect.Descriptor instead.
func (*ClassNamesResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{33}
}

func (x *ClassNamesResponse) GetNameList() []string {
	if x != nil {
		return x.NameList
	}
	return nil
}

type ModelInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *ClassDefinition       `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInstanceResponse) Reset() {
	*x = ModelInstanceResponse{}
	mi := &file_compiler_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInstanceResponse) ProtoMessage() {}

func (x *ModelInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInstanceResponse.ProtoReflect.Descriptor instead.
func (*ModelInstanceResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{34}
}

func (x *ModelInstanceResponse) GetClass() *ClassDefinition {
	if x != nil {
		return x.Class
	}
	return nil
}

type LoadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // 模型路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadFileRequest) Reset() {
	*x = LoadFileRequest{}
	mi := &file_compiler_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadFileRequest) ProtoMessage() {}

func (x *LoadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadFileRequest.ProtoReflect.Descriptor instead.
func (*LoadFileRequest) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{35}
}

func (x *LoadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type LoadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   string                 `protobuf:"bytes,1,opt,name=packageName,proto3" json:"packageName,omitempty"` // 加载解析后的包名
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                 // 返回的信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadFileResponse) Reset() {
	*x = LoadFileResponse{}
	mi := &file_compiler_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadFileResponse) ProtoMessage() {}

func (x *LoadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_compiler_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadFileResponse.ProtoReflect.Descriptor instead.
func (*LoadFileResponse) Descriptor() ([]byte, []int) {
	return file_compiler_proto_rawDescGZIP(), []int{36}
}

func (x *LoadFileResponse) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *LoadFileResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_compiler_proto protoreflect.FileDescriptor

var file_compiler_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x73, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09,
	0x61, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x39, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x6d, 0x63, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x7f, 0x0a, 0x19, 0x53, 0x65,
	0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x73, 0x6d, 0x63, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x2e, 0x61,
	0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x12, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a, 0x1a, 0x53,
	0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x61, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65,
	0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x22, 0x32, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x7c, 0x0a, 0x1e, 0x53, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5a, 0x0a, 0x17, 0x53, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x6d,
	0x63, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x17, 0x53,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x1f, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x54, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x61, 0x64, 0x64,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x73, 0x6d, 0x63, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x61, 0x64, 0x64, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x56, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x2f, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x70, 0x0a, 0x1b, 0x53, 0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x51, 0x0a, 0x14, 0x73, 0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x73, 0x6d, 0x63, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x73,
	0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x1c, 0x53, 0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x48, 0x0a, 0x11, 0x41,
	0x64, 0x64, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x33, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x6d, 0x63, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x41,
	0x64, 0x64, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x69,
	0x63, 0x61, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x69, 0x63, 0x61, 0x50, 0x61, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x74, 0x68,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x74, 0x68,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x2c, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x69, 0x63, 0x61, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0x31, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x69, 0x63,
	0x61, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x50, 0x0a, 0x12, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3f, 0x0a, 0x13, 0x4c, 0x6f, 0x61, 0x64, 0x4c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53,
	0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x66, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65,
	0x4f, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x53, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62,
	0x54, 0x79, 0x70, 0x65, 0x4f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x53,
	0x61, 0x76, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x54, 0x0a, 0x16, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x4c,
	0x0a, 0x17, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x6d, 0x63, 0x2e, 0x73,
	0x79, 0x6e, 0x74, 0x61, 0x78, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x47, 0x0a, 0x11,
	0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x47, 0x0a, 0x12, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x6d, 0x63,
	0x2e, 0x73, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x30,
	0x0a, 0x10, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x45, 0x0a, 0x10, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x41, 0x53, 0x54, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x6d, 0x63, 0x2e, 0x73, 0x79, 0x6e, 0x74, 0x61, 0x78,
	0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x27, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x49, 0x0a, 0x11, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x41, 0x6c, 0x6c, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x41, 0x6c, 0x6c, 0x22, 0x30, 0x0a, 0x12, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4a, 0x0a,
	0x15, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x6d, 0x63, 0x2e, 0x73, 0x79, 0x6e, 0x74,
	0x61, 0x78, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0x25, 0x0a, 0x0f, 0x4c, 0x6f, 0x61,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x22, 0x46, 0x0a, 0x10, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xa8, 0x0a, 0x0a, 0x03, 0x53, 0x4d, 0x43,
	0x12, 0x31, 0x0a, 0x08, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x4c,
	0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x62, 0x72, 0x61,
	0x72, 0x79, 0x12, 0x13, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x37, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x2e,
	0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x2e, 0x50, 0x61,
	0x72, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x37, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x11, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x11, 0x2e,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x41, 0x53, 0x54, 0x12, 0x11, 0x2e, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x41, 0x53, 0x54, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x12, 0x12, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2f, 0x0a,
	0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x11, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x66, 0x12, 0x14,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x54, 0x79, 0x70,
	0x65, 0x4f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a,
	0x0a, 0x41, 0x64, 0x64, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x41, 0x64,
	0x64, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x2e, 0x53, 0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x53,
	0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a,
	0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x15,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x40, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x15, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x5e, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x53,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x49, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x12,
	0x53, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x53, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a,
	0x0f, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x69, 0x63, 0x61, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x17, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x69, 0x63, 0x61, 0x50, 0x61,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x53, 0x65, 0x74, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x69, 0x63, 0x61, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x69, 0x63, 0x61, 0x50, 0x61, 0x74, 0x68, 0x12, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x69, 0x63, 0x61, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x69, 0x63, 0x61, 0x50,
	0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x47, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x53, 0x4d, 0x43, 0x3b, 0x73, 0x6d, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_compiler_proto_rawDescOnce sync.Once
	file_compiler_proto_rawDescData = file_compiler_proto_rawDesc
)

func file_compiler_proto_rawDescGZIP() []byte {
	file_compiler_proto_rawDescOnce.Do(func() {
		file_compiler_proto_rawDescData = protoimpl.X.CompressGZIP(file_compiler_proto_rawDescData)
	})
	return file_compiler_proto_rawDescData
}

var file_compiler_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_compiler_proto_goTypes = []any{
	(*GetErrorsRequest)(nil),                // 0: GetErrorsRequest
	(*GetErrorsResponse)(nil),               // 1: GetErrorsResponse
	(*SetClassAnnotationRequest)(nil),       // 2: SetClassAnnotationRequest
	(*SetClassAnnotationResponse)(nil),      // 3: SetClassAnnotationResponse
	(*DeleteConnectionRequest)(nil),         // 4: DeleteConnectionRequest
	(*DeleteConnectionResponse)(nil),        // 5: DeleteConnectionResponse
	(*SetConnectionAnnotationRequest)(nil),  // 6: SetConnectionAnnotationRequest
	(*SetConnectionAnnotationResponse)(nil), // 7: SetConnectionAnnotationResponse
	(*AddConnectionRequest)(nil),            // 8: AddConnectionRequest
	(*AddConnectionResponse)(nil),           // 9: AddConnectionResponse
	(*DeleteElementRequest)(nil),            // 10: DeleteElementRequest
	(*DeleteElementResponse)(nil),           // 11: DeleteElementResponse
	(*SetElementAnnotationRequest)(nil),     // 12: SetElementAnnotationRequest
	(*SetElementAnnotationResponse)(nil),    // 13: SetElementAnnotationResponse
	(*AddElementRequest)(nil),               // 14: AddElementRequest
	(*AddElementResponse)(nil),              // 15: AddElementResponse
	(*GetModelicaPathRequest)(nil),          // 16: GetModelicaPathRequest
	(*GetModelicaPathResponse)(nil),         // 17: GetModelicaPathResponse
	(*SetModelicaPathRequest)(nil),          // 18: SetModelicaPathRequest
	(*SetModelicaPathResponse)(nil),         // 19: SetModelicaPathResponse
	(*LoadLibraryRequest)(nil),              // 20: LoadLibraryRequest
	(*LoadLibraryResponse)(nil),             // 21: LoadLibraryResponse
	(*GetSubTypeOfResponse)(nil),            // 22: GetSubTypeOfResponse
	(*GetSubTypeOfRequest)(nil),             // 23: GetSubTypeOfRequest
	(*SaveModelResponse)(nil),               // 24: SaveModelResponse
	(*ParserModelCodeRequest)(nil),          // 25: ParserModelCodeRequest
	(*ParserModelCodeResponse)(nil),         // 26: ParserModelCodeResponse
	(*ParserCodeRequest)(nil),               // 27: ParserCodeRequest
	(*ParserCodeResponse)(nil),              // 28: ParserCodeResponse
	(*ClassNameRequest)(nil),                // 29: ClassNameRequest
	(*ModelASTResponse)(nil),                // 30: ModelASTResponse
	(*ModelCodeResponse)(nil),               // 31: ModelCodeResponse
	(*ClassNamesRequest)(nil),               // 32: ClassNamesRequest
	(*ClassNamesResponse)(nil),              // 33: ClassNamesResponse
	(*ModelInstanceResponse)(nil),           // 34: ModelInstanceResponse
	(*LoadFileRequest)(nil),                 // 35: LoadFileRequest
	(*LoadFileResponse)(nil),                // 36: LoadFileResponse
	(*ErrorMessage)(nil),                    // 37: smc.error.errorMessage
	(*Argument)(nil),                        // 38: smc.syntax.argument
	(*SetConnectionAnnotation)(nil),         // 39: smc.ast.SetConnectionAnnotation
	(*AddConnection)(nil),                   // 40: smc.ast.AddConnection
	(*SetElementAnnotation)(nil),            // 41: smc.ast.SetElementAnnotation
	(*AddElement)(nil),                      // 42: smc.ast.AddElement
	(*ClassDefinition)(nil),                 // 43: smc.syntax.classDefinition
}
var file_compiler_proto_depIdxs = []int32{
	37, // 0: GetErrorsResponse.messageList:type_name -> smc.error.errorMessage
	38, // 1: SetClassAnnotationRequest.SetClassAnnotation:type_name -> smc.syntax.argument
	39, // 2: SetConnectionAnnotationRequest.SetConnectionAnnotation:type_name -> smc.ast.SetConnectionAnnotation
	40, // 3: AddConnectionRequest.addConnection:type_name -> smc.ast.AddConnection
	41, // 4: SetElementAnnotationRequest.setElementAnnotation:type_name -> smc.ast.SetElementAnnotation
	42, // 5: AddElementRequest.addElement:type_name -> smc.ast.AddElement
	43, // 6: ParserModelCodeResponse.model:type_name -> smc.syntax.classDefinition
	43, // 7: ParserCodeResponse.model:type_name -> smc.syntax.classDefinition
	43, // 8: ModelASTResponse.model:type_name -> smc.syntax.classDefinition
	43, // 9: ModelInstanceResponse.class:type_name -> smc.syntax.classDefinition
	35, // 10: SMC.LoadFile:input_type -> LoadFileRequest
	20, // 11: SMC.LoadLibrary:input_type -> LoadLibraryRequest
	27, // 12: SMC.ParserCode:input_type -> ParserCodeRequest
	25, // 13: SMC.ParserModelCode:input_type -> ParserModelCodeRequest
	29, // 14: SMC.GetModelCode:input_type -> ClassNameRequest
	29, // 15: SMC.GetModelInstance:input_type -> ClassNameRequest
	29, // 16: SMC.GetModelAST:input_type -> ClassNameRequest
	32, // 17: SMC.GetClassNames:input_type -> ClassNamesRequest
	29, // 18: SMC.Save:input_type -> ClassNameRequest
	23, // 19: SMC.GetSubTypeOf:input_type -> GetSubTypeOfRequest
	14, // 20: SMC.AddElement:input_type -> AddElementRequest
	12, // 21: SMC.SetElementAnnotation:input_type -> SetElementAnnotationRequest
	10, // 22: SMC.DeleteElement:input_type -> DeleteElementRequest
	8,  // 23: SMC.AddConnection:input_type -> AddConnectionRequest
	6,  // 24: SMC.SetConnectionAnnotation:input_type -> SetConnectionAnnotationRequest
	4,  // 25: SMC.DeleteConnection:input_type -> DeleteConnectionRequest
	2,  // 26: SMC.SetClassAnnotation:input_type -> SetClassAnnotationRequest
	18, // 27: SMC.SetModelicaPath:input_type -> SetModelicaPathRequest
	16, // 28: SMC.GetModelicaPath:input_type -> GetModelicaPathRequest
	0,  // 29: SMC.GetErrors:input_type -> GetErrorsRequest
	36, // 30: SMC.LoadFile:output_type -> LoadFileResponse
	21, // 31: SMC.LoadLibrary:output_type -> LoadLibraryResponse
	28, // 32: SMC.ParserCode:output_type -> ParserCodeResponse
	26, // 33: SMC.ParserModelCode:output_type -> ParserModelCodeResponse
	31, // 34: SMC.GetModelCode:output_type -> ModelCodeResponse
	34, // 35: SMC.GetModelInstance:output_type -> ModelInstanceResponse
	30, // 36: SMC.GetModelAST:output_type -> ModelASTResponse
	33, // 37: SMC.GetClassNames:output_type -> ClassNamesResponse
	24, // 38: SMC.Save:output_type -> SaveModelResponse
	22, // 39: SMC.GetSubTypeOf:output_type -> GetSubTypeOfResponse
	15, // 40: SMC.AddElement:output_type -> AddElementResponse
	13, // 41: SMC.SetElementAnnotation:output_type -> SetElementAnnotationResponse
	11, // 42: SMC.DeleteElement:output_type -> DeleteElementResponse
	9,  // 43: SMC.AddConnection:output_type -> AddConnectionResponse
	7,  // 44: SMC.SetConnectionAnnotation:output_type -> SetConnectionAnnotationResponse
	5,  // 45: SMC.DeleteConnection:output_type -> DeleteConnectionResponse
	3,  // 46: SMC.SetClassAnnotation:output_type -> SetClassAnnotationResponse
	19, // 47: SMC.SetModelicaPath:output_type -> SetModelicaPathResponse
	17, // 48: SMC.GetModelicaPath:output_type -> GetModelicaPathResponse
	1,  // 49: SMC.GetErrors:output_type -> GetErrorsResponse
	30, // [30:50] is the sub-list for method output_type
	10, // [10:30] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_compiler_proto_init() }
func file_compiler_proto_init() {
	if File_compiler_proto != nil {
		return
	}
	file_syntax_proto_init()
	file_ast_proto_init()
	file_error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_compiler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compiler_proto_goTypes,
		DependencyIndexes: file_compiler_proto_depIdxs,
		MessageInfos:      file_compiler_proto_msgTypes,
	}.Build()
	File_compiler_proto = out.File
	file_compiler_proto_rawDesc = nil
	file_compiler_proto_goTypes = nil
	file_compiler_proto_depIdxs = nil
}
