version: "3"


networks:
  yssim-net:
    external: true
#  dev:
#    external: true

services:
#  redis:
#    image: redis:latest
#    container_name: redis
#    restart: always
#    ports:
#      - 6379:6379
#    command: redis-server /usr/local/etc/redis/redis.conf
#    volumes:
#      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
#      - ../redis/data/:/data/
#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.8
##    ports:
##      - "2181:2181"
#    expose:
#      - "2181"
#    volumes:
#      - "zookeeper_data:/bitnami"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    networks:
#      - yssim-net
#    container_name: "yssim-zookeeper"
#    restart: always
#  kafka:
#    image: docker.io/bitnami/kafka:3.1
#    ports:
#      - "9092:9092"
#    expose:
#      - "9092"
#    volumes:
#      - "kafka_data:/bitnami"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#    networks:
#      - yssim-net
#    container_name: "yssim-kafka"
#    restart: always
#
#  Jmodelica:
#    image: docker.io/mihoutao/jmodelica:v2.3
##    ports:
##      - "56789:56789"
#    expose:
#      - "56789"
#    volumes:
#      - "../yssim-go/omlibrary/:/omlibrary"
#      - "../yssim-go/public/:/public"
#      - "../yssim-go/JM:/JM"
#      - "../yssim-go/:/code"
#    depends_on:
#      - kafka
#    command: "/usr/bin/supervisord -n -c /JM/supervisor_JModelica.ini"
#    networks:
#      - yssim-net
#    container_name: "yssim-Jmodelica"
#    restart: always
#
#  NOTICE:
#    build:
#      context: "../notice/docker/"
#      dockerfile: "Dockerfile"
#    image: notice:v1.0
#    ports:
#      - "5555:5555"
#    networks:
#      - yssim-net
#    container_name: "yssim-notice"
#    restart: always

#  DOCKER-SERVICE:
#    build:
#      context: "../docker-service/docker/"
#      dockerfile: "Dockerfile"
#    image: docker-service:v1.0
#    ports:
#      - "36790:36790"
#    volumes:
#      - "/var/run:/var/run"
#    networks:
#      - yssim-net
#    container_name: "docker-service"
#    restart: always
##    environment:
##      - sysPath=${sysPath}
#    env_file:
#      - "../docker-service/docker/docker.env"

  Yssim-SERVICE:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: omc-v1
    ports:
      - "4321:4321"
    volumes:
      - "../:/home/simtek/code"
      - "../omlibrary/:/usr/bin/../lib/omlibrary"
    environment:
      - USERNAME=admin
      - PORT=4321
    networks:
      - yssim-net
    container_name: "admin"
    restart: always
    command: "./start.sh"



volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
